// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI69mZ_h4dNH6fYyjvNFl9ICbq9ANjXSM',
    appId: '1:76740649944:web:5da59609dddb642112c8ad',
    messagingSenderId: '76740649944',
    projectId: 'incw12-mad',
    authDomain: 'incw12-mad.firebaseapp.com',
    storageBucket: 'incw12-mad.firebasestorage.app',
    measurementId: 'G-PCRFK9J41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhg0J82MXQi6brW1Y41FicbVwEPg2WOk',
    appId: '1:76740649944:android:5df640654a152adc12c8ad',
    messagingSenderId: '76740649944',
    projectId: 'incw12-mad',
    storageBucket: 'incw12-mad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI69mZ_h4dNH6fYyjvNFl9ICbq9ANjXSM',
    appId: '1:76740649944:web:15219d78c41c143d12c8ad',
    messagingSenderId: '76740649944',
    projectId: 'incw12-mad',
    authDomain: 'incw12-mad.firebaseapp.com',
    storageBucket: 'incw12-mad.firebasestorage.app',
    measurementId: 'G-C8GTYVE94Z',
  );
}
